//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDonHang
    {
        public int CTDonhangID { get; set; }
        public Nullable<int> SanphamID { get; set; }
        public Nullable<int> DonhangID { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> Dongia { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
