//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
            this.CTPhieuXuats = new HashSet<CTPhieuXuat>();
        }
    
        public int DonhangID { get; set; }
        public Nullable<int> KhachhangID { get; set; }
        public Nullable<System.DateTime> Ngaylap { get; set; }
        public Nullable<System.DateTime> Ngaynhanhang { get; set; }
        public string Diachigiaohang { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Trangthai { get; set; }
        public string Hotenkhachhang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuXuat> CTPhieuXuats { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
