//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoangGia
    {
        public int KhoanggiaID { get; set; }
        public Nullable<decimal> Giatren { get; set; }
        public Nullable<decimal> Giaduoi { get; set; }
    }
}
