//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
            this.CTPhieuNhaps = new HashSet<CTPhieuNhap>();
            this.CTPhieuXuats = new HashSet<CTPhieuXuat>();
        }
    
        public int SanphamID { get; set; }
        public Nullable<int> DanhmucID { get; set; }
        public string Tensanpham { get; set; }
        public Nullable<double> Giabandau { get; set; }
        public Nullable<double> Trongluong { get; set; }
        public string Mausac { get; set; }
        public string Imagelink { get; set; }
        public string Memory { get; set; }
        public string Hedieuhanh { get; set; }
        public string VGA { get; set; }
        public string CPUZ { get; set; }
        public string Battery { get; set; }
        public string Phukiendikem { get; set; }
        public string Chedobaohanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuNhap> CTPhieuNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuXuat> CTPhieuXuats { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
